notesApp/user/forms.py
from flask_wtf import FlaskForm
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms import PasswordField, StringField, SubmitField, ValidationError, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo

from ..models import User, Career, Role


class UserUpdateForm(FlaskForm):
    """
    Form for user to update their information
    """

    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])

    career = QuerySelectField(query_factory=lambda: Career.query.all(),
                               get_label="name")
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                               get_label="name")
    submit = SubmitField('Submit')

class NoteForm(FlaskForm):
    """
    Adding a note for a user
    """
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Note', validators=[DataRequired()])
    submit = SubmitField('Submit')

notesApp/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

notesApp/user/views.py
from flask import flash, redirect, render_template, url_for, request
from flask_login import login_required, current_user

from . import user
from forms import UserUpdateForm, NoteForm
from .. import db
from ..models import User, Career, Note


@user.route('/viewprofile', methods=['GET', 'POST'])
@login_required
def viewprofile():
    """
    Handle requests to the /register route
    Add an notetaker to the database through the registration form
    """
    user = current_user
    form=UserUpdateForm(obj=user)
    form.populate_obj(user)
    if form.validate_on_submit():

        form.populate_obj(user)

        db.session.commit()

        flash('You have successfully edited your profile!')
    return render_template('user/user.html', title="View Profile",
                           user=user, form=form, action='Edit')


@user.route('/notes')
@login_required
def list_notes():

    """
    List all roles
    """
    user = current_user
    try:
        notes = user.notes
    except:
        notes = False

    return render_template('user/notes.html', user=user,
                           notes=notes, title='Notes')

@user.route('/notes/add', methods=['GET', 'POST'])
@login_required
def add_note():
    """
    Add a role to the database
    """
    add_note = True
    user = current_user
    form = NoteForm()
    if form.validate_on_submit():
        note = Note(title=form.title.data,
                    body=form.body.data)

        try:
            # add role to the database
            user.notes.append(note)
            db.session.add(note)
            db.session.commit()
            flash('You have successfully added a new note to the user.')
        except:
            # in case role name already exists
            flash('Error: .')
        # redirect to the roles page
        return redirect(url_for('user.list_notes'))

    # load role template
    return render_template('user/note.html', add_role=add_note,
                           form=form, title='Add Note')


@user.route('/notes/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_note(id):
    """
    Edit a role
    """

    add_note = False

    note = Note.query.get_or_404(id)
    form = NoteForm(obj=note)
    if form.validate_on_submit():
        note.title = form.title.data
        note.body = form.body.data
        db.session.add(note)
        db.session.commit()
        flash('You have successfully edited the note.')

        # redirect to the roles page
        return redirect(url_for('user.list_notes'))

    form.body.data = note.body
    form.title.data = note.title
    return render_template('user/note.html', add_role=add_note,
                           form=form, title="Edit Note")

@user.route('/notes/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_note(id):
    """
    Delete a role from the database
    """

    note = Note.query.get_or_404(id)
    db.session.delete(note)
    db.session.commit()
    flash('You have successfully deleted the role.')

    # redirect to the roles page
    return redirect(url_for('user.list_notes'))

    return render_template(title="Delete Note")

notesApp/templates/user/interactive.html
{% extends "base.html" %}
{% block body %}
	<head>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script type=text/javascript>
			$(function() {
			  $('a#process_input').bind('click', function() {
				$.getJSON('/background_process', {
				  proglang: $('input[name="proglang"]').val(),
				}, function(data) {
				  $("#result").text(data.result);
				});
				return false;
			  });
			});
		</script>
	</head>

	<body>
		<div class='container'>
		<h3>Welcome! Which is the best programming language of them all?</h3>
			<form>
				<input type=text size=5 name=proglang>
				<a href=# id=process_input><button class='btn btn-default'>Submit</button></a>
			</form>
		<p id=result></p>
		</div>
	</body>
{% endblock %}

notesApp/templates/user/note.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_note %}
        Add Note
    {% else %}
        Edit Note
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_role %}
                <h1>Add Note</h1>
            {% else %}
                <h1>Edit Note</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

notesApp/templates/user/notes.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Notes{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">My Current Notes</h1>
        {% if user.career.name %}
        <h3 style="text-align:center;">{{user.career.name}} : {{ user.role.name }} </h3>
        {% else %}
        <h3 style="text-align:center;">{{ user.username}} </h3>
        {% endif %}

        {% if notes %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Title </th>
                  <th width="40%"> Body </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for note in notes %}
                <tr>
                  <td> {{ note.title }} </td>
                  <td> {{ note.body }} </td>
                  <td>
                    <a href="{{ url_for('user.edit_note', id=note.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('user.delete_note', id=note.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No notes have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('user.add_note') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Role
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

notesApp/templates/user/user.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}View Profile{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1> Welcome {{ user.username }}</h1>
            <div class="center">
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}