notesApp/home/__init__.py
# app/admin/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

notesApp/home/views.py
from flask import abort, render_template, request, jsonify
from flask_login import current_user, login_required

from . import home
from notesApp.models import *

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title="Dashboard")


# @user.route('/interactive/', methods=['GET', 'POST'])
# def interactive():
#
#     return render_template("user/interactive.html")
#
# @user.route('/background_process')
# def background_process():
#     # cols = getColumns(User)
#     # UsersList = User.query.all()
#
#     try:
#         lang = request.args.get('proglang', 0, type=str)
#         if lang.lower() == 'python':
#
#             return jsonify(result='You are wise')
#         else:
#             return jsonify(result='Try again.')
#     except Exception as e:
#         return str(e)

@home.route('/tables')
def viewtables():
    return render_template("home/view_tables.html")

@home.route('/gettables', methods=['GET'])
def gettables():

    table =  str(request.args.get('mytable')).lower()

    if table == 'user':
        ideas = User.query.order_by('username')
        return getTable(ideas)
    if table == 'career':
        ideas = Career.query.all()
        return getTable(ideas)
    if table == 'role':
        ideas = Role.query.all()
        return getTable(ideas)
    if table == 'note':
        ideas = Note.query.all()
        return getTable(ideas)
    else:
        error = {
            'status': '404',
            'msg': 'unable to retrieve ideas'
        }
        return jsonify(error)

def getColumns(modelclass):
    from sqlalchemy import inspect
    mapper = inspect(modelclass)
    return [c.key for c in mapper.attrs]

def getTable(ideas):
    # ideas = User.query.order_by('username')
    # d = [i.serialize() for i in ideas]

    if ideas:
        m = []
        querylist = []
        for i in ideas:
            try:
                q = i.serialize()
                querylist.append(q)
            except:
                m.append('error')

        data = {
            'status': 'OK',
            'ideas': querylist,
            'msg': m
        }
        return jsonify(data)
    else:
        error = {
            'status': 404,
            'ideas': None,
            'msg': 'unable to retrieve ideas'
        }
        return jsonify(error)

notesApp/templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>For fancy administrators </h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

notesApp/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>NoteTaking Dashboard</h1>
                    <h3></h3>
                    <hr class="intro-divider">
                </div>
            </div>
        </div>
    </div>
     <h2><a href="{{ url_for('home.viewtables') }}">Search the DataBase Tables</a></h2>
     <h2><a href="{{ url_for('user.list_notes') }}">View, Edit, Add, and Delete Your Notes</a></h2>
     <h2><a href="{{ url_for('user.viewprofile') }}">View and Edit Your Profile</a></h2>
</div>
{% endblock %}

notesApp/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Note Taking 101 Home Page</h1>
                    <h3>Taking notes one word at a time</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
        <h2><a href="{{ url_for('home.viewtables') }}">Search the DataBase Tables</a></h2>
    </div>
</div>
{% endblock %}

notesApp/templates/home/view_tables.html
{% extends "base.html" %}
{% block title %}Tables{% endblock %}
{% block body %}
	<head>
		<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/scroller/1.4.2/css/scroller.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/colreorder/1.3.2/css/colReorder.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/buttons/1.2.1/css/buttons.dataTables.min.css" rel="stylesheet">
        <link href="https://cdn.datatables.net/rowreorder/1.1.2/css/rowReorder.dataTables.min.css"rel="stylesheet">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/URI.js/1.18.1/URI.js"></script>
        <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/scroller/1.4.2/js/dataTables.scroller.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.2.1/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/colreorder/1.3.2/js/dataTables.colReorder.min.js"></script>
        <script src="https://cdn.datatables.net/rowreorder/1.1.2/js/dataTables.rowReorder.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js"></script>
    </head>
<div class="tables-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="tables-message">
                    <h1>Search the DataBase tables</h1>
                    <h3>User, Role, Career, Note</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>
<form class="myform" method="GET">
    <p>
        <label for="tablelookup">Table Name: </label>
        <input id="tablelookup" type="text" name="tablelookup" value=User>
        <button id='searchbutton' class="search" type="button"><span>Search</span></button>
    </p>
</form>
<table id="table" class="dataTable sig-datatable" width="100%">
    </table>
</body>

<script>
  $(document).ready(function() {

    $('#searchbutton').click(function(){

        $.ajax({

          'type': 'GET',
          'url': '/gettables',
          'data': {'mytable': $('#tablelookup').val()},



          success: function(data) {

              if (data.status == 404){
                alert('Redirecting Back Home\n' +  data.msg)
                location.assign('/')
                }

              var columns=[];

              for (var k in data.ideas[0])
                  {
                      columns[columns.length] = {title: k, data:k, defaultContent:"-"};
                  }

              if ( $.fn.dataTable.isDataTable( '#table' ) ) {
                    table.destroy()
                    $('#table').empty()
                    table = $('#table').DataTable( {
                        columns: columns,
                        bAutoWidth: true,
                        data: data.ideas
                    } )
              }
              // Otherwise, we can initialize the Table.
              else {
                    table = $('#table').DataTable( {
                        columns: columns,
                        bAutoWidth: true,
                        data: data.ideas
                    } )

              }
          }

       })
     })
    })
    </script>
{% endblock %}